name: Manual Run Scripts

on: workflow_dispatch

defaults:
  run:
     working-directory: scripts

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run longcalcs
        run: python longcalc.py
      - name: Commit
        if: github.ref == 'refs/heads/master'
        uses: EndBug/add-and-commit@v5
        with:
          message: Updating longcalc data
          add: | 
            data/de.txt data/hi.txt data/ma.txt data/me.txt data/mi.txt data/nc.txt data/nd.txt data/oh.txt data/tx.txt data/ut.txt data/wa.txt data/wi.txt data/wv.txt
          author_name: GitHub Actions
          author_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
